platform :ios, "8.0"
inhibit_all_warnings!
use_frameworks!

pod 'BabyBluetooth','~> 0.7.0'
pod 'SDAutoLayout'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage', '~>3.7.3'
pod 'SDWebImage-ProgressView'
pod 'AFNetworking', '~> 2.6.3'
pod 'IQKeyboardManager', '~> 3.3.7'
pod 'Masonry', '~> 0.6.4'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'FMDB'
pod 'UITextView+Placeholder'